import type { WorkflowJob } from "@/types/workflow";

type ResearchReportFormat = "html" | "doc";

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function getSelectedIdea(job: WorkflowJob) {
  return job.ideas.find((idea) => idea.id === job.selectedIdeaId) ?? null;
}

function getResearchSummary(job: WorkflowJob) {
  const latestResearchEvent = [...(job.automationEvents ?? [])]
    .filter((event) => event.type === "research")
    .sort((left, right) => right.updatedAt.localeCompare(left.updatedAt))[0];

  return typeof latestResearchEvent?.payload?.summaryText === "string"
    ? latestResearchEvent.payload.summaryText
    : "";
}

function buildSources(job: WorkflowJob) {
  return job.research.sources
    .map(
      (source) => `
        <li>
          <strong>${escapeHtml(source.title)}</strong><br />
          ${
            source.source.startsWith("http://") || source.source.startsWith("https://")
              ? `<a href="${escapeHtml(source.source)}" target="_blank" rel="noreferrer">${escapeHtml(source.source)}</a><br />`
              : `<span>${escapeHtml(source.source)}</span><br />`
          }
          <small>${escapeHtml(source.insight)}</small>
        </li>
      `
    )
    .join("");
}

function buildGaps(job: WorkflowJob) {
  return job.research.gaps
    .map((gap) => `<li>${escapeHtml(gap)}</li>`)
    .join("");
}

export function buildResearchReport(job: WorkflowJob, format: ResearchReportFormat) {
  const selectedIdea = getSelectedIdea(job);
  const summary = getResearchSummary(job) || "No research document available yet.";
  const generatedAt = new Date().toLocaleString("th-TH", {
    dateStyle: "long",
    timeStyle: "short"
  });

  const html = `<!doctype html>
<html lang="th">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(job.brief.title || job.seedKeyword)} - Research Report</title>
  <style>
    body {
      font-family: "Segoe UI", Arial, sans-serif;
      margin: 36px;
      color: #111827;
      line-height: 1.7;
      background: #ffffff;
    }
    h1,h2,h3 { color: #111827; }
    h1 { font-size: 28px; margin-bottom: 10px; }
    h2 { font-size: 18px; margin-top: 28px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
    .meta {
      display: grid;
      grid-template-columns: 180px 1fr;
      gap: 8px 16px;
      margin: 20px 0 28px;
    }
    .meta strong { color: #374151; }
    .panel {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 14px;
      padding: 18px 20px;
      margin-bottom: 18px;
    }
    .summary p {
      margin: 0 0 14px;
      white-space: pre-wrap;
    }
    ul {
      margin: 0;
      padding-left: 20px;
    }
    li {
      margin-bottom: 10px;
    }
    .footer {
      margin-top: 36px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      color: #6b7280;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <h1>Research Document</h1>
  <div class="meta">
    <strong>Project</strong><span>${escapeHtml(job.client)}</span>
    <strong>Seed keyword</strong><span>${escapeHtml(job.seedKeyword)}</span>
    <strong>Selected topic</strong><span>${escapeHtml(selectedIdea?.title || "-")}</span>
    <strong>Search intent</strong><span>${escapeHtml(selectedIdea?.searchIntent || "-")}</span>
    <strong>Audience</strong><span>${escapeHtml(job.research.audience || "-")}</span>
    <strong>Objective</strong><span>${escapeHtml(job.research.objective || "-")}</span>
    <strong>Generated at</strong><span>${escapeHtml(generatedAt)}</span>
  </div>

  <h2>Working Research Document</h2>
  <div class="panel summary">
    ${summary
      .split(/\n{2,}/)
      .map((paragraph) => `<p>${escapeHtml(paragraph.trim())}</p>`)
      .join("")}
  </div>

  <h2>Research Gaps</h2>
  <div class="panel">
    <ul>${buildGaps(job)}</ul>
  </div>

  <h2>Sources</h2>
  <div class="panel">
    <ul>${buildSources(job)}</ul>
  </div>

  <div class="footer">
    Generated by Auto Post Content
  </div>
</body>
</html>`;

  if (format === "doc") {
    return html;
  }

  return html;
}
