ALTER TABLE "ContentBrief"
ADD COLUMN "publishStatus" TEXT NOT NULL DEFAULT 'draft',
ADD COLUMN "categoryIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "tagIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "featuredImageUrl" TEXT NOT NULL DEFAULT '';
